# TODO: migrate IMAGE_ROOTFS_INSTALL_CLI_TOOLS and IMAGE_ROOTFS_INSTALL_EXTENDED_UTILS
# into a debug/field-research layer, then remove from this config.
# See also: enapter-linux-minimal.conf for the stripped-down variant.
require enapter-linux.inc

# Podman container support
# podman-compose recipe is missing python3-unixadmin and python3-json as dependencies
IMAGE_ROOTFS_INSTALL_CONTAINERS = "\
    crun \
    enapter-docker-compose \
    enapter-podman-prepare \
    netavark \
    podman \
    podman-compose \
    python3-json \
    python3-unixadmin \
"

VIRTUAL-RUNTIME_container_engine ?= "podman"
VIRTUAL-RUNTIME_container_runtime ?= "crun"
VIRTUAL-RUNTIME_container_networking ?= "netavark"
VIRTUAL-RUNTIME_container_dns ?= "aardvark-dns"
VIRTUAL-RUNTIME_container_orchestration ?= ""

PREFERRED_VERSION_podman = "5.4.1"
PREFERRED_VERSION_podman-compose = "1.5.0"
PREFERRED_VERSION_aardvark-dns = "1.14.0"
PREFERRED_VERSION_netavark = "1.14.1"

# The next two groups were excluded from the new (minimal) enapter-industrial-linux image
# and are expected to be excluded from the regular image too and moved into a debug layer
IMAGE_ROOTFS_INSTALL_CLI_TOOLS = "\
    mosquitto-clients \
    postgresql-client \
"

IMAGE_ROOTFS_INSTALL_EXTENDED_UTILS = "\
    efibootmgr \
    elfutils \
    gawk \
    gdb \
    grpcurl \
    htop \
    i2c-tools \
    iotop \
    lsof \
    mc \
    mokutil \
    mtr \
    nano \
    netcat \
    nmap \
    p7zip \
    screen \
    socat \
    strace \
    systemd-analyze \
    tcpdump \
    trace-cmd \
    smartmontools \
    vim \
"
