# SPDX-FileCopyrightText: 2024 Enapter <developers@enapter.com>
# SPDX-License-Identifier: Apache-2.0

env:
  DISTRO: null
  DISTRO_VERSION: null
  DL_DIR: /home/build/downloads
  GPL_SOURCES_ARTIFACT_NAME: null
  IMG_ARTIFACT_NAME: null
  IMG_FILE_ARTIFACT_NAME: null
  INITRAMFS_SPDX_ARTIFACT_NAME: null
  MODSIGN_SIGNING_CERT: null
  MODSIGN_SIGNING_KEY: null
  NVDCVE_API_KEY: null
  RAUC_CERT: null
  RAUC_KEY: null
  RAUC_KEYRING: null
  RAUC_UPDATE_ARTIFACT_NAME: null
  ROOTFS_SPDX_ARTIFACT_NAME: null
  SECURE_BOOT_SIGNING_CERT: null
  SECURE_BOOT_SIGNING_CERT_DER: null
  SECURE_BOOT_SIGNING_KEY: null
  SSTATE_DIR: /home/build/sstate-cache
  TMPDIR: /home/build/tmp
  UPDATE_ARTIFACT_NAME: null
  VEX_ARTIFACT_NAME: null
  VMDK_ARTIFACT_NAME: null

repos:
  bitbake:
    url: 'git://git.openembedded.org/bitbake'
    tag: 'yocto-5.0.15'
    path: "bitbake"
    layers:
      bitbake: excluded

  meta-enapter-linux:
    layers:
      meta-enapter-linux:

  openembedded-core:
    url: 'git://git.openembedded.org/openembedded-core'
    tag: 'yocto-5.0.15'
    layers:
      meta:

  meta-enapter:
    url: 'https://github.com/enapter/meta-enapter'
    tag: 'v3.0.0-rc8'
    layers:
      meta-enapter-core:

  meta-intel:
    url: 'git://git.yoctoproject.org/meta-intel.git'
    commit: '5d153e35b4e752505efeae368f188fac5e31cf33'

  meta-openembedded:
    url: 'git://git.openembedded.org/meta-openembedded'
    commit: '7a5075cef77b5f7af454e9868e1d0019f2fd1394'
    layers:
      meta-filesystems:
      meta-initramfs:
      meta-networking:
      meta-oe:
      meta-perl:
      meta-python:
      meta-webserver:

  meta-rauc:
    url: 'https://github.com/rauc/meta-rauc.git'
    commit: 'e9d65639be4d8f150fbc7435e2ea399e2671fde1'

  meta-virtualization:
    url: 'git://git.yoctoproject.org/meta-virtualization'
    commit: '8b1543e121deda2445f80f74d85c10316d5b31f4'

local_conf_header:
  10-base: |
    CONF_VERSION = "2"
    SPDX_PRETTY = "1"
    IMAGE_FSTYPES = "wic ext4"
    SKIP_META_VIRT_SANITY_CHECK = "1"
    INHERIT += "rm_work archiver vex"
    COPY_LIC_MANIFEST = "1"
    COPY_LIC_DIRS = "1"
    LICENSE_CREATE_PACKAGE = "1"
    ARCHIVER_MODE[diff] = "1"
