# SPDX-FileCopyrightText: 2024 Enapter <developers@enapter.com>
# SPDX-License-Identifier: Apache-2.0

header:
  version: 17

distro: enapter-industrial-linux
target: enapter-industrial-linux-image
machine: intel-corei7-64

env:
  DISTRO_VERSION: null
  DL_DIR: /home/build/downloads
  SECURE_BOOT_SIGNING_CERT: null
  SECURE_BOOT_SIGNING_CERT_DER: null
  SECURE_BOOT_SIGNING_KEY: null
  SSTATE_DIR: /home/build/sstate-cache
  TMPDIR: /home/build/tmp
  IMG_ARTIFACT_NAME: null
  IMG_FILE_ARTIFACT_NAME: null
  UPDATE_ARTIFACT_NAME: null
  VMDK_ARTIFACT_NAME: null

repos:
  meta-enapter-linux:
    layers:
      meta-enapter-linux:

  poky:
    url: 'git://git.yoctoproject.org/poky.git'
    tag: 'yocto-5.0.3'
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-enapter:
    url: 'https://github.com/enapter/meta-enapter'
    tag: 'v2.5.3-dev1'
    layers:
      meta-enapter-core:

  meta-intel:
    url: 'git://git.yoctoproject.org/meta-intel.git'
    commit: 'c2bc8e27e9cc83654a23e8d89525fd9b1e781eb6'

  meta-openembedded:
    url: 'git://git.openembedded.org/meta-openembedded'
    commit: '735ae0310870ffce07ce0c55c4f87c20ac161ff9'
    layers:
      meta-filesystems:
      meta-initramfs:
      meta-networking:
      meta-oe:
      meta-perl:
      meta-python:
      meta-webserver:

  meta-virtualization:
    url: 'git://git.yoctoproject.org/meta-virtualization'
    commit: 'e5878c864aacd24fe8f09ab7221f0ada13cd22d3'

local_conf_header:
  10-base: |
    CONF_VERSION = "2"
    IMAGE_FSTYPES = "wic ext4"
    SKIP_META_VIRT_SANITY_CHECK = "1"
    INHERIT += "rm_work"
