# <folder_name> <repository_path> <revision/branch/tag>"
repositories/meta-enapter https://github.com/enapter/meta-enapter release/3.0
repositories/meta-intel git://git.yoctoproject.org/meta-intel.git cfb0e237cf3f25ffb128bd55e3e72eb0fb2ca096
repositories/meta-openembedded git://git.openembedded.org/meta-openembedded 1235dd4ed4a57e67683c045ad76b6a0f9e896b45
repositories/meta-virtualization git://git.yoctoproject.org/meta-virtualization 54b806b1985f3989722ee308e1073530fe3328c1
repositories/poky git://git.yoctoproject.org/poky.git yocto-5.0.3
