# <folder_name> <repository_path> <revision/branch/tag>"
repositories/meta-cloud-services git://git.yoctoproject.org/meta-cloud-services 61d37af7f412aa1ecacdf584faf0fba300f7d58e
repositories/meta-enapter https://github.com/enapter/meta-enapter release/3.0
repositories/meta-intel git://git.yoctoproject.org/meta-intel.git c8cd0317ec19332bce86697f3413a82b9828b329
repositories/meta-openembedded git://git.openembedded.org/meta-openembedded 4a7bb77f7ebe0ac8be5bab5103d8bd993e17e18d
repositories/meta-security git://git.yoctoproject.org/meta-security 11ea91192d43d7c2b0b95a93aa63ca7e73e38034
repositories/meta-virtualization git://git.yoctoproject.org/meta-virtualization 37c06acf58f9020bccfc61954eeefe160642d5f3
repositories/poky git://git.yoctoproject.org/poky.git 83793ccd865e3e72563e6d5733b6bd02943feb8a
